spring:
  application:
    name: event-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

server:
  port: 8080

app:
  jwt:
    secret: Zm9yLWRldi1vbmx5LWNoYW5nZS10aGlzLXNlY3JldC1rZXk=
    expiration-ms: 86400000
